export const scriptContent = {
    "props": {
        "pageProps": {
            "company": {
                "slug": "amazon",
                "id": 4,
                "parentId": null,
                "name": "Amazon",
                "description": "Amazon.com, Inc. operates through three segments: North America, International, and Amazon Web Services (AWS).\n\nThe company engages in the retail sale of consumer products and subscriptions in North America and internationally, selling merchandise and content purchased through physical and online stores.\n\nThey also provide cloud services that include compute, storage, database, analytics, machine learning, and others.\n\nThe company serves consumers, sellers, developers, enterprises, and content creators. Amazon.com, Inc. was incorporated in 1994 and is headquartered in Seattle, Washington.\n",
                "website": "https://www.amazon.com",
                "twitter": "amazon",
                "linkedin": "company/amazon",
                "crunchbase": "organization/amazon",
                "year_founded": 1995,
                "emp_count": 865406,
                "ticker": "AMZN",
                "color": [
                    255,
                    154,
                    1
                ],
                "hq_address": "410 Terry Ave N, Seattle, WA 98109, USA",
                "hq_city": "Seattle",
                "hq_state_code": "WA",
                "icon": "https://static.levels.fyi/logos/128/amazon.webp",
                "icon_large": "https://static.levels.fyi/amazonlogo.png",
                "company_type": "public",
                "vesting_schedule": "5,15,40/2,40/2",
                "vesting_type": "RSU",
                "vesting_detail": "Backloaded vesting schedule",
                "general_levels": "L4,L5,L6,L7,L8,L9,L10",
                "aliases": "AWS, Amazon Web Services, Amazon.com, IMDb, Goodreads, Shopbop, AWS Elemental, Woot, Amazon Robotics, Amazon Pay",
                "tags": [
                    "E-commerce",
                    "Internet",
                    "E-Commerce & Marketplaces",
                    "Technology",
                    "B2C"
                ],
                "related_companies_slugs": [
                    {
                        "icon": "https://i.imgur.com/7vP0GdO.png",
                        "name": "eBay",
                        "slug": "ebay"
                    },
                    {
                        "icon": "https://img.logo.dev/etsy.com?token=pk_Ez-J4YOpSS-Bjtug_T41Dw",
                        "name": "Etsy",
                        "slug": "etsy"
                    },
                    {
                        "icon": "https://i.imgur.com/iGJqQhU.png",
                        "name": "Wayfair",
                        "slug": "wayfair"
                    },
                    {
                        "icon": "https://img.logo.dev/wish.com?token=pk_Ez-J4YOpSS-Bjtug_T41Dw",
                        "name": "Wish",
                        "slug": "wish"
                    },
                    {
                        "icon": "https://img.logo.dev/chewy.com?token=pk_Ez-J4YOpSS-Bjtug_T41Dw",
                        "name": "Chewy",
                        "slug": "chewy"
                    }
                ],
                "insights": [
                    {
                        "icon": "DateRange",
                        "insight": "Known for a backloaded vesting schedule"
                    },
                    {
                        "icon": "HistoryEdu",
                        "insight": "Typically offers 2 years of signing bonuses"
                    },
                    {
                        "icon": "FormatListBulleted",
                        "insight": "Interview Tip: Prepare an example for each of Amazon's [Leadership Principles](https://www.levels.fyi/blog/amazon-leadership-principles.html) using the [STAR method](https://www.levels.fyi/blog/applying-star-method-resumes.html)"
                    },
                    {
                        "icon": "MonetizationOn",
                        "insight": "Base salary caps out at $350k for all employees regardless of level"
                    }
                ],
                "icon_greyscale": "https://img.logo.dev/amazon.fr?greyscale=true&token=pk_Ez-J4YOpSS-Bjtug_T41Dw",
                "perks_verified": null,
                "benefits_page": "https://www.amazondelivers.jobs/about/benefits/#:~:text=Medical%2C%20prescription%20drug%2C%20dental%20and,improve%20your%20overall%20well%2Dbeing",
                "career_page": null,
                "pay_schedule": "Bi-Weekly",
                "industry": "Tech",
                "hq_state": "Washington",
                "hq_latitude": 47.6221922,
                "hq_longitude": -122.336546,
                "ein": "911646860",
                "employee_count_range": "100K+",
                "estimated_annual_revenue": "$10B+",
                "last_updated": "2022-01-01T00:00:00.000Z",
                "clearbit_not_supported": false,
                "estimated_valuation": "911.62",
                "jobBoardSlug": null,
                "cover_image": null,
                "country": {
                    "slug": "united-states",
                    "id": 254,
                    "name": "United States",
                    "code": "USA",
                    "codeIso2": "US",
                    "population": "278058881",
                    "defaultCurrency": "USD"
                }
            },
            "jobFamily": "Software Engineer",
            "jobFamilySlug": "software-engineer",
            "levels": {
                "company": "Amazon",
                "company_slug": "amazon",
                "companyIcon": "https://static.levels.fyi/amazonlogo.png",
                "color": [
                    255,
                    154,
                    1
                ],
                "skill_spectrum": 95,
                "generic": false,
                "job_family": "Software Engineer",
                "job_family_slug": "software-engineer",
                "levels": [
                    {
                        "description": null,
                        "titles": [
                            "SDE I",
                            "L4"
                        ],
                        "titleSlugs": [
                            "sde-i",
                            "l4"
                        ],
                        "order": 0,
                        "target_bonus_percentage": null,
                        "percent_workforce": 22
                    },
                    {
                        "description": null,
                        "titles": [
                            "SDE II",
                            "L5"
                        ],
                        "titleSlugs": [
                            "sde-ii",
                            "l5"
                        ],
                        "order": 1,
                        "target_bonus_percentage": null,
                        "percent_workforce": 22
                    },
                    {
                        "description": null,
                        "titles": [
                            "SDE III",
                            "L6",
                            "Senior SDE"
                        ],
                        "titleSlugs": [
                            "sde-iii",
                            "l6",
                            "senior-sde"
                        ],
                        "order": 2,
                        "target_bonus_percentage": null,
                        "percent_workforce": 28
                    },
                    {
                        "description": null,
                        "titles": [
                            "Principal SDE",
                            "L7"
                        ],
                        "titleSlugs": [
                            "principal-sde",
                            "l7"
                        ],
                        "order": 3,
                        "target_bonus_percentage": null,
                        "percent_workforce": 12
                    },
                    {
                        "description": null,
                        "titles": [
                            "Senior Principal SDE",
                            "L8"
                        ],
                        "titleSlugs": [
                            "senior-principal-sde",
                            "l8"
                        ],
                        "order": 4,
                        "target_bonus_percentage": null,
                        "percent_workforce": 10
                    },
                    {
                        "description": null,
                        "titles": [
                            "Distinguished Engineer",
                            "L10"
                        ],
                        "titleSlugs": [
                            "distinguished-engineer",
                            "l10"
                        ],
                        "order": 5,
                        "target_bonus_percentage": null,
                        "percent_workforce": 7
                    }
                ],
                "hasSalaryLevelData": true
            },
            "averages": [
                {
                    "count": 16,
                    "count_last_12_months": 201,
                    "samples": [
                        {
                            "uuid": "9f771319-ec73-40da-98d9-40d34f493bdf",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE I",
                            "focusTag": "Security",
                            "yearsOfExperience": 1,
                            "yearsAtCompany": 0,
                            "offerDate": "2025-01-13T11:56:54.37+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 68601.6,
                            "totalCompensation": 70333.96,
                            "avgAnnualStockGrantValue": 1732.3637,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "4e55b269-1b99-41a4-aa19-d1740bbe49f0",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE I",
                            "focusTag": "API Development (Back-End)",
                            "yearsOfExperience": 5,
                            "yearsAtCompany": 5,
                            "offerDate": "2024-12-31T05:59:47.685+00:00",
                            "location": "Winnipeg, MB, Canada",
                            "dmaId": 960,
                            "countryId": 43,
                            "baseSalary": 80837.65,
                            "totalCompensation": 82231.4,
                            "avgAnnualStockGrantValue": 1393.7525,
                            "avgAnnualBonusValue": 0,
                            "gender": "male",
                            "otherDetails": null
                        },
                        {
                            "uuid": "0e768fe3-0206-466c-9136-87884e85b570",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE I",
                            "focusTag": "API Development (Back-End)",
                            "yearsOfExperience": 1,
                            "yearsAtCompany": 0,
                            "offerDate": "2025-01-01T04:59:59.999+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 78606.23,
                            "totalCompensation": 84171.28,
                            "avgAnnualStockGrantValue": 5565.043000000001,
                            "avgAnnualBonusValue": 0,
                            "gender": "male",
                            "otherDetails": null
                        },
                        {
                            "uuid": "6d7c12c6-9427-4a8f-9933-fbb0d14c9445",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE I",
                            "focusTag": "API Development (Back-End)",
                            "yearsOfExperience": 3,
                            "yearsAtCompany": 0,
                            "offerDate": "2024-12-19T11:01:16.171+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 83381.39,
                            "totalCompensation": 90329.84000000001,
                            "avgAnnualStockGrantValue": 6948.4496,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "db3b4023-0e22-4b63-a72c-05b8ce64037a",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE I",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 1,
                            "yearsAtCompany": 0,
                            "offerDate": "2025-01-06T19:53:08.247+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 78792.86,
                            "totalCompensation": 91518.265,
                            "avgAnnualStockGrantValue": 4358.012699999999,
                            "avgAnnualBonusValue": 8367.384,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "7410efba-2196-4369-963c-7f0c9ad38af5",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE I",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 1,
                            "yearsAtCompany": 1,
                            "offerDate": "2025-01-01T04:12:57.171+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 81528.84,
                            "totalCompensation": 95465.39,
                            "avgAnnualStockGrantValue": 13936.554,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "fdd02084-8697-4862-a202-ff9dd02d1117",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE I",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 3,
                            "yearsAtCompany": 2,
                            "offerDate": "2024-12-19T01:47:22.873+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 82443.08499999999,
                            "totalCompensation": 101668.26000000001,
                            "avgAnnualStockGrantValue": 19225.174,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "79d54e4e-a235-407e-8cd5-1d858a9fecf2",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE I",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 1,
                            "yearsAtCompany": 1,
                            "offerDate": "2025-01-08T15:52:54.482+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 83378.784,
                            "totalCompensation": 111171.71500000001,
                            "avgAnnualStockGrantValue": 27792.929,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "ad006406-91b9-4ee2-a647-b7aa36a209fa",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE I",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 0,
                            "yearsAtCompany": 0,
                            "offerDate": "2025-01-15T07:49:47.229+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 79340.454,
                            "totalCompensation": 112098.02,
                            "avgAnnualStockGrantValue": 19347.079999999998,
                            "avgAnnualBonusValue": 13410.489,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "fce77b2d-db20-4209-8ce3-e84eea651432",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE I",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 0,
                            "yearsAtCompany": 0,
                            "offerDate": "2025-01-12T02:32:53.525+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 78885.62000000001,
                            "totalCompensation": 113155.396,
                            "avgAnnualStockGrantValue": 19236.167999999998,
                            "avgAnnualBonusValue": 15033.609999999999,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "f517d38c-d0a7-44b8-b33b-145abc06e9ee",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE I",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 2,
                            "yearsAtCompany": 2,
                            "offerDate": "2025-01-16T04:40:39.191+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 80108.39,
                            "totalCompensation": 114938.126,
                            "avgAnnualStockGrantValue": 34829.735,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "c50eada3-6fe8-4821-944e-92d6a99a6751",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE I",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 3,
                            "yearsAtCompany": 3,
                            "offerDate": "2025-01-16T20:11:44.65+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 80551.36,
                            "totalCompensation": 118743.81,
                            "avgAnnualStockGrantValue": 38192.455,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "201ffbe1-d57e-4973-9908-37c1a14cb48f",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE I",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 2,
                            "yearsAtCompany": 2,
                            "offerDate": "2024-12-29T21:04:34.927+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 78392.2,
                            "totalCompensation": 120016.37,
                            "avgAnnualStockGrantValue": 41624.176,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "cf75d69f-2f9e-461b-a574-3e539953a694",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE I",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 4,
                            "yearsAtCompany": 2,
                            "offerDate": "2025-01-02T21:32:42.175+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 90280.29,
                            "totalCompensation": 121531.15,
                            "avgAnnualStockGrantValue": 31250.868000000002,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "d09cd53b-9ef4-4203-a48f-4b1bc5c70d59",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE I",
                            "focusTag": "ML / AI",
                            "yearsOfExperience": 2,
                            "yearsAtCompany": 2,
                            "offerDate": "2024-12-26T01:12:44.734+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 77323.09,
                            "totalCompensation": 133051.44,
                            "avgAnnualStockGrantValue": 55728.35,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        }
                    ],
                    "bonus": 2301,
                    "base": 80058,
                    "stock": 21809,
                    "total": 104168,
                    "levelIndex": 0,
                    "level": "sde-i",
                    "levelPageUrl": "/companies/amazon/salaries/software-engineer/levels/sde-i/locations/canada",
                    "secondaryLevelName": "L4",
                    "primaryLevelName": "SDE I",
                    "shortestLevelName": "L4",
                    "formattedValues": {
                        "total": "$104K",
                        "base": "$80K",
                        "bonus": "$2.3K",
                        "stock": "$22K"
                    },
                    "rawValues": {
                        "total": 104168,
                        "base": 80058,
                        "bonus": 2301,
                        "stock": 21809
                    }
                },
                {
                    "count": 22,
                    "count_last_12_months": 365,
                    "samples": [
                        {
                            "uuid": "34eeeb54-b8e8-47ff-a646-136e30edfbeb",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "API Development (Back-End)",
                            "yearsOfExperience": 8,
                            "yearsAtCompany": 5,
                            "offerDate": "2025-01-06T20:24:23.234+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 100454.14,
                            "totalCompensation": 117894.09000000001,
                            "avgAnnualStockGrantValue": 17439.955,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "319ade8a-0827-4f6a-8965-46cd950793c3",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 4,
                            "yearsAtCompany": 4,
                            "offerDate": "2024-12-20T02:45:38.495+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 99802.13,
                            "totalCompensation": 120594.24,
                            "avgAnnualStockGrantValue": 20792.11,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "9815a83b-e9f4-4c44-a07b-3636b3e5ad5f",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 5,
                            "yearsAtCompany": 4,
                            "offerDate": "2025-01-01T05:59:59.999+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 86953.8,
                            "totalCompensation": 121735.32,
                            "avgAnnualStockGrantValue": 34781.520000000004,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "746697a2-f7ce-4404-a628-6b12243ea62a",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 4,
                            "yearsAtCompany": 4,
                            "offerDate": "2025-01-02T04:52:36.354+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 99468.92,
                            "totalCompensation": 127292.4,
                            "avgAnnualStockGrantValue": 27823.475,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "9a289fca-c6de-40ad-9569-c1c4c4fe1a87",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 4,
                            "yearsAtCompany": 4,
                            "offerDate": "2024-12-19T00:53:54.482+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 103808.02,
                            "totalCompensation": 131490.16,
                            "avgAnnualStockGrantValue": 27682.14,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "e522f3bc-0255-433c-a9b4-78ffe49dc0e9",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 12,
                            "yearsAtCompany": 7,
                            "offerDate": "2025-01-14T02:54:38.898+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 104290.87,
                            "totalCompensation": 132101.78,
                            "avgAnnualStockGrantValue": 27810.9,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "de174fd3-4715-4500-8a4d-2567324fe6c1",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 10,
                            "yearsAtCompany": 3,
                            "offerDate": "2025-01-10T16:48:15.136+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 110842.86,
                            "totalCompensation": 138553.57,
                            "avgAnnualStockGrantValue": 27710.714,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "c02101b3-27f0-4a18-8787-fa0235b804aa",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 5,
                            "yearsAtCompany": 5,
                            "offerDate": "2025-01-14T23:49:27.988+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 104496.84999999999,
                            "totalCompensation": 139329.13,
                            "avgAnnualStockGrantValue": 34832.282999999996,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "7970de9f-7f41-40a1-a817-d700eb25143e",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 14,
                            "yearsAtCompany": 5,
                            "offerDate": "2025-01-05T01:04:11.978+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 112836.74,
                            "totalCompensation": 142603.49,
                            "avgAnnualStockGrantValue": 29766.747,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "11e44859-30b2-4dee-b5b1-a9c4e4c1bbb5",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "API Development (Back-End)",
                            "yearsOfExperience": 3,
                            "yearsAtCompany": 3,
                            "offerDate": "2024-12-21T13:42:27.965+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 97778.336,
                            "totalCompensation": 143175.42,
                            "avgAnnualStockGrantValue": 45397.083,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "40886df0-4c09-4ac0-8fd9-d0b5919b9bff",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 2,
                            "yearsAtCompany": 2,
                            "offerDate": "2025-01-16T15:49:42.083+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 104245.93000000001,
                            "totalCompensation": 152894.03999999998,
                            "avgAnnualStockGrantValue": 48648.106,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "4427d1fb-96b2-4f0e-9305-7602f257f1bd",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 14,
                            "yearsAtCompany": 7,
                            "offerDate": "2025-01-14T06:05:11.287+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 115549.065,
                            "totalCompensation": 154482.56,
                            "avgAnnualStockGrantValue": 38933.5,
                            "avgAnnualBonusValue": 0,
                            "gender": "male",
                            "otherDetails": null
                        },
                        {
                            "uuid": "fa7e5587-b2bb-4e46-a460-f23172914250",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 5,
                            "yearsAtCompany": 3,
                            "offerDate": "2024-12-23T18:23:00.063+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 105732.14,
                            "totalCompensation": 161380.65,
                            "avgAnnualStockGrantValue": 55648.494999999995,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "94d7d82f-1082-498d-be84-0fb02571384f",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "ML / AI",
                            "yearsOfExperience": 4,
                            "yearsAtCompany": 0,
                            "offerDate": "2024-12-23T06:53:31.254+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 139225.83000000002,
                            "totalCompensation": 163590.36000000002,
                            "avgAnnualStockGrantValue": 24364.521,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "27d2f857-728c-4cdb-9589-d241bd89cb64",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 2,
                            "yearsAtCompany": 2,
                            "offerDate": "2025-01-04T19:13:45.718+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 95509.72,
                            "totalCompensation": 164734.71000000002,
                            "avgAnnualStockGrantValue": 69224.99,
                            "avgAnnualBonusValue": 0,
                            "gender": "male",
                            "otherDetails": "Stock appreciation, 308 shares vesting in upcoming compensation year.\n\nPromoted in 2023 Q3, only received base increase"
                        },
                        {
                            "uuid": "70b0ab7f-6144-4983-8d9c-246889784ff4",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "Data",
                            "yearsOfExperience": 7,
                            "yearsAtCompany": 2,
                            "offerDate": "2025-01-11T01:45:05.376+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 110178.04,
                            "totalCompensation": 165267.06,
                            "avgAnnualStockGrantValue": 55089.02,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "af9ef0f9-f1d6-42ef-9cb0-83e24b6bc96b",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE II",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 2,
                            "yearsAtCompany": 2,
                            "offerDate": "2024-12-18T23:27:34.405+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 112138.275,
                            "totalCompensation": 174437.32,
                            "avgAnnualStockGrantValue": 62299.04,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        }
                    ],
                    "bonus": 0,
                    "base": 107961,
                    "stock": 39740,
                    "total": 147701,
                    "levelIndex": 1,
                    "level": "sde-ii",
                    "levelPageUrl": "/companies/amazon/salaries/software-engineer/levels/sde-ii/locations/canada",
                    "secondaryLevelName": "L5",
                    "primaryLevelName": "SDE II",
                    "shortestLevelName": "L5",
                    "formattedValues": {
                        "total": "$148K",
                        "base": "$108K",
                        "bonus": "$0",
                        "stock": "$40K"
                    },
                    "rawValues": {
                        "total": 147701,
                        "base": 107961,
                        "bonus": 0,
                        "stock": 39740
                    }
                },
                {
                    "count": 20,
                    "count_last_12_months": 68,
                    "samples": [
                        {
                            "uuid": "c94a20c4-2167-4be1-9a24-e3ca14551e36",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "API Development (Back-End)",
                            "yearsOfExperience": 9,
                            "yearsAtCompany": 9,
                            "offerDate": "2024-12-20T18:22:30.476+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 139269.45,
                            "totalCompensation": 167123.34999999998,
                            "avgAnnualStockGrantValue": 27853.893,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "46da2dbc-305c-46a7-a1c1-151514bbc50f",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 15,
                            "yearsAtCompany": 5,
                            "offerDate": "2024-11-11T03:54:41.289+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 129311.28000000001,
                            "totalCompensation": 172415.04,
                            "avgAnnualStockGrantValue": 43103.76,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "ae12bc05-12b8-491f-bd3d-a1b69d1643d6",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "API Development (Back-End)",
                            "yearsOfExperience": 11,
                            "yearsAtCompany": 6,
                            "offerDate": "2025-01-02T22:08:00.105+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 124960.95,
                            "totalCompensation": 173556.87,
                            "avgAnnualStockGrantValue": 48595.924,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "30f02641-c590-4c17-9f5f-d8dbb0f3ed15",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 4,
                            "yearsAtCompany": 4,
                            "offerDate": "2025-01-04T17:18:10.3+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 145372.47999999998,
                            "totalCompensation": 190368.73,
                            "avgAnnualStockGrantValue": 44996.246,
                            "avgAnnualBonusValue": 0,
                            "gender": "male",
                            "otherDetails": null
                        },
                        {
                            "uuid": "6da2a1f6-aea6-4da6-9db3-6aefe43b702d",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 7,
                            "yearsAtCompany": 4,
                            "offerDate": "2024-11-01T20:48:08.417+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 136183.15000000002,
                            "totalCompensation": 193523.41999999998,
                            "avgAnnualStockGrantValue": 57340.27,
                            "avgAnnualBonusValue": 0,
                            "gender": "male",
                            "otherDetails": null
                        },
                        {
                            "uuid": "dfacf01b-bf89-41fe-b4df-6a2f4ab876e8",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "Security",
                            "yearsOfExperience": 12,
                            "yearsAtCompany": 3,
                            "offerDate": "2025-01-17T04:25:15.292+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 159769.38,
                            "totalCompensation": 194501.84999999998,
                            "avgAnnualStockGrantValue": 34732.47,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "1ff960de-ed45-4243-9c91-126ff4b0e411",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 12,
                            "yearsAtCompany": 10,
                            "offerDate": "2024-11-16T07:14:19.209+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 127655.045,
                            "totalCompensation": 195028.55,
                            "avgAnnualStockGrantValue": 67373.5,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "a83b2113-91d3-416a-9b92-0da422ca3746",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "API Development (Back-End)",
                            "yearsOfExperience": 20,
                            "yearsAtCompany": 4,
                            "offerDate": "2024-11-19T05:43:19.194+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 139063.7,
                            "totalCompensation": 199681.23,
                            "avgAnnualStockGrantValue": 60617.516,
                            "avgAnnualBonusValue": 0,
                            "gender": "male",
                            "otherDetails": null
                        },
                        {
                            "uuid": "9dcad4ca-37b2-4ea7-9ad2-d1727a35409a",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 7,
                            "yearsAtCompany": 7,
                            "offerDate": "2024-11-13T02:39:01.905+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 114679.14600000001,
                            "totalCompensation": 207855.96000000002,
                            "avgAnnualStockGrantValue": 93176.8,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "41740d3e-97af-4756-a320-f531cbe76f47",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 17,
                            "yearsAtCompany": 3,
                            "offerDate": "2024-12-18T02:05:51.729+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 139712.13,
                            "totalCompensation": 239712.13,
                            "avgAnnualStockGrantValue": 100000,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "f3fb1574-e87d-43e9-8e42-d2dfa6cfb994",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 8,
                            "yearsAtCompany": 6,
                            "offerDate": "2024-11-20T01:44:47.694+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 150413.09999999998,
                            "totalCompensation": 243525.97,
                            "avgAnnualStockGrantValue": 93112.87,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "762490c4-3ce9-435b-966f-41e16512aaa9",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 9,
                            "yearsAtCompany": 8,
                            "offerDate": "2024-12-12T19:35:46.215+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 138225.66,
                            "totalCompensation": 248250.88999999998,
                            "avgAnnualStockGrantValue": 110025.23,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "ec665036-b32a-4ea7-ba3f-818c42841bfd",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 17,
                            "yearsAtCompany": 5,
                            "offerDate": "2025-01-02T18:28:24.014+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 135287.49,
                            "totalCompensation": 256699.34,
                            "avgAnnualStockGrantValue": 121411.85,
                            "avgAnnualBonusValue": 0,
                            "gender": "male",
                            "otherDetails": null
                        },
                        {
                            "uuid": "99cc98ca-b2d3-42ae-a9cc-6d72c90d016b",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 25,
                            "yearsAtCompany": 8,
                            "offerDate": "2024-11-17T22:15:58.062+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 141931.55,
                            "totalCompensation": 283863.1,
                            "avgAnnualStockGrantValue": 141931.55,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "854ce530-5a3e-405c-9f56-4665c2970b78",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 12,
                            "yearsAtCompany": 6,
                            "offerDate": "2025-01-07T19:47:18.469+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 135971.4,
                            "totalCompensation": 285888.6,
                            "avgAnnualStockGrantValue": 149917.19,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "c9918f63-912c-43a5-b007-667cb5d7b277",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 18,
                            "yearsAtCompany": 2,
                            "offerDate": "2024-11-23T19:16:24.508+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 160938.44999999998,
                            "totalCompensation": 289689.2,
                            "avgAnnualStockGrantValue": 128750.76000000001,
                            "avgAnnualBonusValue": 0,
                            "gender": "male",
                            "otherDetails": null
                        },
                        {
                            "uuid": "2347dbc2-f825-4505-a601-da2f7f46140c",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "SDE III",
                            "focusTag": "Full Stack",
                            "yearsOfExperience": 20,
                            "yearsAtCompany": 2,
                            "offerDate": "2024-10-31T19:19:51.577+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 158844.82,
                            "totalCompensation": 302595.8,
                            "avgAnnualStockGrantValue": 143750.96,
                            "avgAnnualBonusValue": 0,
                            "gender": "male",
                            "otherDetails": null
                        }
                    ],
                    "bonus": 0,
                    "base": 138586,
                    "stock": 88469,
                    "total": 227056,
                    "levelIndex": 2,
                    "level": "sde-iii",
                    "levelPageUrl": "/companies/amazon/salaries/software-engineer/levels/sde-iii/locations/canada",
                    "secondaryLevelName": "L6",
                    "primaryLevelName": "SDE III",
                    "shortestLevelName": "L6",
                    "formattedValues": {
                        "total": "$227K",
                        "base": "$139K",
                        "bonus": "$0",
                        "stock": "$88K"
                    },
                    "rawValues": {
                        "total": 227056,
                        "base": 138586,
                        "bonus": 0,
                        "stock": 88469
                    }
                },
                {
                    "count": 13,
                    "count_last_12_months": 4,
                    "samples": [
                        {
                            "uuid": "b1324d49-77c0-45cb-abe8-5af9337118f8",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "Principal SDE",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 10,
                            "yearsAtCompany": 6,
                            "offerDate": "2022-04-08T15:07:43.045+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 182662.9,
                            "totalCompensation": 257662.89999999997,
                            "avgAnnualStockGrantValue": 75000,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "f8213724-5ef3-4d3d-8bed-01036a93cfc2",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "Principal SDE",
                            "focusTag": "API Development (Back-End)",
                            "yearsOfExperience": 18,
                            "yearsAtCompany": 12,
                            "offerDate": "2022-04-13T18:33:31.678+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 185486.66,
                            "totalCompensation": 318432.04,
                            "avgAnnualStockGrantValue": 132945.37,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "ffc89c55-3ac6-4637-b9a4-c3de3cfd7702",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "Principal SDE",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 10,
                            "yearsAtCompany": 6,
                            "offerDate": "2022-09-21T16:32:17.484+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 174325.97,
                            "totalCompensation": 328104.33999999997,
                            "avgAnnualStockGrantValue": 138345.29,
                            "avgAnnualBonusValue": 15433.089,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "4d2549d8-23f1-48d5-b88b-ea55a6b3a8f7",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "Principal SDE",
                            "focusTag": "Data",
                            "yearsOfExperience": 15,
                            "yearsAtCompany": 10,
                            "offerDate": "2024-04-10T19:40:55.752+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 168124.97,
                            "totalCompensation": 328940.16,
                            "avgAnnualStockGrantValue": 160815.19,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "66384519-b402-4b52-8485-a90907ffb357",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "Principal SDE",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 14,
                            "yearsAtCompany": 10,
                            "offerDate": "2024-11-06T15:20:11.805+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 165137.93999999997,
                            "totalCompensation": 330275.87999999995,
                            "avgAnnualStockGrantValue": 165137.93999999997,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "4e3a229e-1258-4afb-91ca-585d3598acb6",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "Principal SDE",
                            "focusTag": "DevOps",
                            "yearsOfExperience": 12,
                            "yearsAtCompany": 12,
                            "offerDate": "2024-05-06T03:53:11.622+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 168073.97,
                            "totalCompensation": 350763.10000000003,
                            "avgAnnualStockGrantValue": 182689.12,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "6e244712-aada-464c-98f9-f9db56ed3995",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "Principal SDE",
                            "focusTag": "General",
                            "yearsOfExperience": 15,
                            "yearsAtCompany": 10,
                            "offerDate": "2022-12-27T18:55:42.819+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 184971.44,
                            "totalCompensation": 406937.16000000003,
                            "avgAnnualStockGrantValue": 221965.73,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "9fb119d9-b960-4649-86e4-bf58c3ec9cf1",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "Principal SDE",
                            "focusTag": "General",
                            "yearsOfExperience": 15,
                            "yearsAtCompany": 8,
                            "offerDate": "2022-09-23T18:21:03.751+00:00",
                            "location": "Toronto, ON, Canada",
                            "dmaId": 950,
                            "countryId": 43,
                            "baseSalary": 183890.6,
                            "totalCompensation": 441337.43,
                            "avgAnnualStockGrantValue": 257446.84,
                            "avgAnnualBonusValue": 0,
                            "gender": "male",
                            "otherDetails": null
                        },
                        {
                            "uuid": "b5165bb7-db86-4de7-8015-209f182270a9",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "Principal SDE",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 22,
                            "yearsAtCompany": 5,
                            "offerDate": "2022-09-05T06:42:56.664+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 190065.64,
                            "totalCompensation": 456157.56,
                            "avgAnnualStockGrantValue": 266091.92000000004,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        },
                        {
                            "uuid": "15ea1ebc-dc10-4657-acb4-e90ca1c7c97f",
                            "company": "Amazon",
                            "title": "Software Engineer",
                            "jobFamily": "Software Engineer",
                            "level": "Principal SDE",
                            "focusTag": "Distributed Systems (Back-End)",
                            "yearsOfExperience": 12,
                            "yearsAtCompany": 6,
                            "offerDate": "2022-08-20T21:41:38.129+00:00",
                            "location": "Vancouver, BC, Canada",
                            "dmaId": 984,
                            "countryId": 43,
                            "baseSalary": 200000,
                            "totalCompensation": 500000,
                            "avgAnnualStockGrantValue": 300000,
                            "avgAnnualBonusValue": 0,
                            "gender": null,
                            "otherDetails": null
                        }
                    ],
                    "bonus": 1187,
                    "base": 178583,
                    "stock": 197043,
                    "total": 376814,
                    "levelIndex": 3,
                    "level": "principal-sde",
                    "levelPageUrl": "/companies/amazon/salaries/software-engineer/levels/principal-sde/locations/canada",
                    "secondaryLevelName": "L7",
                    "primaryLevelName": "Principal SDE",
                    "shortestLevelName": "L7",
                    "formattedValues": {
                        "total": "$377K",
                        "base": "$179K",
                        "bonus": "$1.2K",
                        "stock": "$197K"
                    },
                    "rawValues": {
                        "total": 376814,
                        "base": 178583,
                        "bonus": 1187,
                        "stock": 197043
                    }
                }
            ],
            "percentiles": {
                "base_salary": {
                    "p10": 78606.234,
                    "p25": 80837.65,
                    "p50": 99468.92,
                    "p75": 111223.11,
                    "p90": 139225.83
                },
                "tc": {
                    "p10": 84171.277,
                    "p25": 101629.76,
                    "p50": 129235.666,
                    "p75": 159871.215,
                    "p90": 201524.873
                },
                "bonus": {
                    "p10": 0,
                    "p25": 0,
                    "p50": 0,
                    "p75": 0,
                    "p90": 0
                },
                "stock_grant": {
                    "p10": 5565.043,
                    "p25": 20792.11,
                    "p50": 29766.746,
                    "p75": 48648.105,
                    "p90": 62299.043
                },
                "locationName": "United States"
            },
            "median": {
                "uuid": "e522f3bc-0255-433c-a9b4-78ffe49dc0e9",
                "title": "Software Engineer",
                "jobFamily": "Software Engineer",
                "level": "SDE II",
                "focusTag": "Full Stack",
                "yearsOfExperience": 12,
                "yearsAtCompany": 7,
                "yearsAtLevel": 7,
                "offerDate": "Tue Jan 14 2025 02:54:38 GMT+0000 (Coordinated Universal Time)",
                "location": "Toronto, ON, Canada",
                "workArrangement": "office",
                "compPerspective": "employee",
                "cityId": 1206,
                "dmaId": 950,
                "countryId": 43,
                "exchangeRate": 1.43829,
                "baseSalary": 104290.8742,
                "baseSalaryCurrency": "CAD",
                "salaryFormat": "gross",
                "employmentType": "full_time",
                "totalCompensation": 132101.774,
                "firstYearTotalCompensation": 132101.774,
                "avgAnnualStockGrantValue": 27810.8998,
                "firstYearStockGrantValue": 27810.8998,
                "stockGrantCurrency": "CAD",
                "avgAnnualBonusValue": null,
                "firstYearBonusValue": null,
                "bonusCurrency": null,
                "salesComp": null,
                "gender": null,
                "ethnicity": null,
                "education": null,
                "otherDetails": null,
                "companyInfo": {
                    "name": "Amazon",
                    "icon": "https://static.levels.fyi/logos/128/amazon.webp",
                    "registered": true
                },
                "stockType": "stock",
                "count": 28759
            },
            "generatedOccupationSchema": {
                "@context": "http://schema.googleapis.com/",
                "@type": "OccupationAggregationByEmployer",
                "sampleSize": 71,
                "industry": "Tech",
                "yearsExperienceMin": 0,
                "yearsExperienceMax": 25,
                "name": "Software Engineer",
                "description": "Designs and develops software products for a company",
                "experienceRequirements": "Minimum of 0 years of experience",
                "mainEntityOfPage": {
                    "@type": "WebPage",
                    "lastReviewed": "2025-01-18T11:10:41.007Z"
                },
                "estimatedSalary": [
                    {
                        "@context": "https://schema.org/",
                        "@type": "MonetaryAmountDistribution",
                        "name": "total",
                        "currency": "USD",
                        "unitText": "YEAR",
                        "duration": "P1Y",
                        "percentile10": "84171",
                        "percentile25": "101630",
                        "median": "129236",
                        "percentile75": "159871",
                        "percentile90": "201525"
                    },
                    {
                        "@context": "https://schema.org/",
                        "@type": "MonetaryAmountDistribution",
                        "name": "base",
                        "currency": "USD",
                        "unitText": "YEAR",
                        "duration": "P1Y",
                        "percentile10": "78606",
                        "percentile25": "80838",
                        "median": "99469",
                        "percentile75": "111223",
                        "percentile90": "139226"
                    },
                    {
                        "@context": "https://schema.org/",
                        "@type": "MonetaryAmountDistribution",
                        "name": "equity",
                        "currency": "USD",
                        "unitText": "YEAR",
                        "duration": "P1Y",
                        "percentile10": "5565",
                        "percentile25": "20792",
                        "median": "29767",
                        "percentile75": "48648",
                        "percentile90": "62299"
                    },
                    {
                        "@context": "https://schema.org/",
                        "@type": "MonetaryAmountDistribution",
                        "name": "bonus",
                        "currency": "USD",
                        "unitText": "YEAR",
                        "duration": "P1Y",
                        "percentile10": null,
                        "percentile25": null,
                        "median": null,
                        "percentile75": null,
                        "percentile90": null
                    }
                ],
                "occupationLocation": [
                    {
                        "@context": "https://schema.org/",
                        "@type": "Country",
                        "name": "Canada"
                    }
                ],
                "hiringOrganization": {
                    "@context": "https://schema.org/",
                    "@type": "Organization",
                    "name": "Amazon"
                }
            },
            "breadcrumbSchema": "{\"@context\":\"https://schema.org\",\"@type\":\"BreadcrumbList\",\"itemListElement\":[{\"@type\":\"ListItem\",\"position\":1,\"name\":\"Companies\",\"item\":\"https://levels.fyi/companies\"},{\"@type\":\"ListItem\",\"position\":2,\"name\":\"Amazon Salaries\",\"item\":\"https://levels.fyi/companies/amazon\"},{\"@type\":\"ListItem\",\"position\":3,\"name\":\"Software Engineer\",\"item\":\"https://levels.fyi/companies/amazon/salaries/software-engineer\"},{\"@type\":\"ListItem\",\"position\":4,\"name\":\"Canada\",\"item\":\"https://levels.fyi/companies/amazon/salaries/software-engineer/locations/canada\"}]}",
            "vestMessage": "Given Amazon has an irregular vesting schedule (5%, 15%, 40%, 40%), the average total compensation is calculated by dividing the total stock grant evenly by 4. We also average out the sum of the sign on bonuses over 4 years to calculate the total bonus.",
            "isShowingAllLevels": false,
            "shouldShowSalaryRange": false,
            "questionsAndAnswers": [
                {
                    "question": "What is the highest Software Engineer salary at Amazon in Canada?",
                    "answer": "The highest paying salary package reported for a Software Engineer at Amazon in Canada sits at a yearly total compensation of $376,814. This includes base salary as well as any potential stock compensation and bonuses."
                },
                {
                    "question": "How much do Amazon Software Engineer employees get paid in Canada?",
                    "answer": "The median yearly total compensation reported at Amazon for the Software Engineer role in Canada is $129,236."
                }
            ],
            "companySalariesJobFamilyFAQSchema": "{\"@context\":\"https://schema.org\",\"@type\":\"FAQPage\",\"mainEntity\":[{\"@type\":\"Question\",\"name\":\"What is the highest Software Engineer salary at Amazon in Canada?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"The highest paying salary package reported for a Software Engineer at Amazon in Canada sits at a yearly total compensation of $376,814. This includes base salary as well as any potential stock compensation and bonuses.\"}},{\"@type\":\"Question\",\"name\":\"How much do Amazon Software Engineer employees get paid in Canada?\",\"acceptedAnswer\":{\"@type\":\"Answer\",\"text\":\"The median yearly total compensation reported at Amazon for the Software Engineer role in Canada is $129,236.\"}}]}",
            "locationMeta": {
                "name": "Canada",
                "slug": "canada",
                "type": "country",
                "id": 43,
                "displayName": "Canada",
                "state": null,
                "stateCode": null,
                "countryCodeIso2": "CA",
                "countryName": "Canada",
                "locationCurrency": "CAD"
            },
            "locationCurrency": "CAD",
            "locationExchangeRate": 1.41,
            "companyJfTitles": [
                {
                    "count": 8,
                    "title": "Mobile Software Engineer",
                    "total": 187000,
                    "title_slug": "mobile-software-engineer"
                },
                {
                    "count": 156,
                    "title": "Frontend Software Engineer",
                    "total": 280000,
                    "title_slug": "frontend-software-engineer"
                },
                {
                    "count": 45,
                    "title": "Machine Learning Engineer",
                    "total": 330000,
                    "title_slug": "machine-learning-engineer"
                },
                {
                    "count": 1328,
                    "title": "Backend Software Engineer",
                    "total": 261000,
                    "title_slug": "backend-software-engineer"
                },
                {
                    "count": 2622,
                    "title": "Full-Stack Software Engineer",
                    "total": 255000,
                    "title_slug": "full-stack-software-engineer"
                },
                {
                    "count": 285,
                    "title": "Networking Engineer",
                    "total": 290000,
                    "title_slug": "networking-engineer"
                },
                {
                    "count": 173,
                    "title": "Quality Assurance (QA) Software Engineer",
                    "total": 194000,
                    "title_slug": "quality-assurance-(qa)-software-engineer"
                },
                {
                    "count": 266,
                    "title": "Data Engineer",
                    "total": 250000,
                    "title_slug": "data-engineer"
                },
                {
                    "count": 113,
                    "title": "Production Software Engineer",
                    "total": 275000,
                    "title_slug": "production-software-engineer"
                },
                {
                    "count": 324,
                    "title": "Security Software Engineer",
                    "total": 340000,
                    "title_slug": "security-software-engineer"
                },
                {
                    "count": 16,
                    "title": "DevOps Engineer",
                    "total": 211500,
                    "title_slug": "devops-engineer"
                },
                {
                    "count": 15,
                    "title": "Site Reliability Engineer",
                    "total": 200000,
                    "title_slug": "site-reliability-engineer"
                },
                {
                    "count": 6,
                    "title": "Crypto Engineer",
                    "total": 190000,
                    "title_slug": "crypto-engineer"
                },
                {
                    "count": 9,
                    "title": "Virtual Reality Software Engineer",
                    "total": 236000,
                    "title_slug": "virtual-reality-software-engineer"
                },
                {
                    "count": 91,
                    "title": "Systems Engineer",
                    "total": 300000,
                    "title_slug": "systems-engineer"
                },
                {
                    "count": 316,
                    "title": "Business Intelligence Engineer",
                    "total": 179500,
                    "title_slug": "business-intelligence-engineer"
                },
                {
                    "count": 4,
                    "title": "Web Developer",
                    "total": 170000,
                    "title_slug": "web-developer"
                },
                {
                    "count": 10,
                    "title": "Video Game Software Engineer",
                    "total": 228000,
                    "title_slug": "video-game-software-engineer"
                },
                {
                    "count": 508,
                    "title": "Research Scientist",
                    "total": 386000,
                    "title_slug": "research-scientist"
                },
                {
                    "count": 3,
                    "title": "Android Engineer",
                    "total": 197000,
                    "title_slug": "android-engineer"
                },
                {
                    "count": 21,
                    "title": "Embedded Systems Software Engineer",
                    "total": 303700,
                    "title_slug": "embedded-systems"
                }
            ],
            "locationSlug": "canada"
        },
        "__N_SSG": true
    },
    "page": "/companies/[company]/salaries/[job-family]/locations/[location]",
    "query": {
        "company": "amazon",
        "job-family": "software-engineer",
        "location": "canada"
    },
    "buildId": "dlwYmJSym98sbUKzcK2Dl",
    "assetPrefix": "https://www.levels.fyi",
    "isFallback": false,
    "gsp": true,
    "customServer": true,
    "scriptLoader": []
}